#!/bin/bash
# AutoPubMonitor configuration

export AUTOPUB_BASE_DIR="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor"
export AUTOPUB_DATA_DIR="/root/AutoPublishDATA"
export AUTOPUB_AUTO_PUBLISH_DIR="/root/AutoPublishDATA/AutoPublish"
export AUTOPUB_TRANSCRIPTION_DATA_DIR="/root/AutoPublishDATA/transcription_data"
export AUTOPUB_LOGS_DIR="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/logs"
export AUTOPUB_LOGS_AUTOPUB_DIR="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/logs-autopub"
export AUTOPUB_VIDEOS_DB_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/videos_db.csv"
export AUTOPUB_PROCESSED_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/processed.csv"
export AUTOPUB_QUEUE_LIST_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/queue_list.txt"
export AUTOPUB_TEMP_QUEUE_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/temp_queue.txt"
export AUTOPUB_CHECKED_LIST_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/checked_list.txt"
export AUTOPUB_QUEUE_LOCK_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/queue.lock"
export AUTOPUB_QUEUE_PIPE_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/queue.pipe"
export AUTOPUB_AUTOPUB_SCRIPT_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/autopub.py"
export AUTOPUB_AUTOPUB_SH_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/autopub.sh"
export AUTOPUB_MONITOR_SCRIPT_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/monitor_autopublish.sh"
export AUTOPUB_PROCESS_QUEUE_SCRIPT_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/process_queue.sh"
export AUTOPUB_SYNC_SCRIPT_PATH="/home/lachlan/DiskMech/Projects/autopub-monitor/autopub_monitor/autopub_sync.sh"
export AUTOPUB_UPLOAD_URL="http://localhost:8081/upload"
export AUTOPUB_PROCESS_URL="http://localhost:8081/video-processing"
export AUTOPUB_PUBLISH_URL="http://lazyingart:8081/publish"
export AUTOPUB_DEFAULT_PUBLISH_PLATFORMS_PUBLISH_XHS="True"
export AUTOPUB_DEFAULT_PUBLISH_PLATFORMS_PUBLISH_BILIBILI="True"
export AUTOPUB_DEFAULT_PUBLISH_PLATFORMS_PUBLISH_DOUYIN="True"
export AUTOPUB_DEFAULT_PUBLISH_PLATFORMS_PUBLISH_SHIPINHAO="True"
export AUTOPUB_DEFAULT_PUBLISH_PLATFORMS_PUBLISH_Y2B="True"
export AUTOPUB_SYNC_SOURCE="/root/jianguoyun/AutoPublishDATA/AutoPublish"
export AUTOPUB_SYNC_TARGET="/root/AutoPublishDATA/AutoPublish"
export AUTOPUB_SYNC_INTERVAL="10"
export AUTOPUB_MIN_VIDEO_LENGTH="7"
export AUTOPUB_VIDEO_FILE_EXTENSIONS="['mp4', 'mov', 'avi', 'flv', 'wmv', 'mkv']"
export AUTOPUB_CONDA_PATH="/root/miniconda3/bin/activate"
export AUTOPUB_CONDA_ENV="autopub-video"